FE=(70)
GB=(80)
ITCS=(85)
CP=(75)
print("--- Your Score ---")
print("Foundation English :",FE,"score")
print("General Busines :",GB,"score")
print("Introduction to Computer System",ITCS,"score")
print("Computer Programming :",CP,"score")